### ISSUE TITLE
Empty orbit selection window

### ISSUE THREAD

**Issue by antonioltg91** [linuxgurugamer/KRASH#17] opened 2016-11-29 15:23 UTC
Hello, I have a problem. 
When I go in the orbit tab. Everything from the windows disappear, I have installed both KerbalKonstruct and Outer Planets (maybe this is the problem)
In the Kerbin tab i only have the lauchpad and the runway and in the landed only kerbin (I don't know if also this is a bug)

This message is repeated in the logs
```
[EXC 15:56:10.117] NullReferenceException: Object reference not set to an instance of an object
	KRASH.LaunchGUI.drawSelectorWindow (Int32 id)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[ERR 15:56:10.119] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)
```
full log
http://antonioltg.com/ksp/KSP1.log

**Comment by linuxgurugamer** [comment] 2016-11-29 17:32
Please try it without those two mods and let me know what happens

**Comment by antonioltg91** [comment] 2016-11-30 01:12
Ok the problem is TarsierSpaceTech, I don't know what is the problem in particular.
But I still have only Kerbin and the Mun available
Here is the full log http://antonioltg.com/ksp/KSP2.log

**Comment by linuxgurugamer** [comment] 2016-11-30 17:09
Among other things, it looks like you have ActiveStruts installed (?), which is very interesting since it hasn't been around for a couple of years.  Also, update KVV,  you have a dev version

**Comment by antonioltg91** [comment] 2016-11-30 17:23
Maybe it's from IR?
However I'm using TarsierSpaceTech parts without the plugins and your mod is working (still with only mun and kerbin)

**Comment by linuxgurugamer** [comment] 2016-11-30 17:46
Oh, that could be.
Anyway, I'll look into this later, I assume that without Tarsier it works ok?

**Comment by antonioltg91** [comment] 2016-12-01 15:21
Yes it works fine without Tarsier.
I think is some other mod that show me only kerbin an the mun, because on the sandbox works with every planet.

**Comment by JPLRepo** [comment] 2017-11-04 20:59
Seems to me to be a bug with this mod. Not Tarsier Space Tech.
The error is IMGUI failure in this mod as per the first post above.
I would suggest this mod needs to handle errors such as:
NullReferenceException: Object reference not set to an instance of an object
	KRASH.LaunchGUI.drawSelectorWindow (Int32 id)

**Comment by linuxgurugamer** [comment] 2017-11-05 16:22
I've just tried to replicate this, and I can't.  It's possible it was fixed in an earlier update.
Can you (or someone) see if you can replicate it, and if you can, please post the steps you did to do so?

**Comment by linuxgurugamer** [comment] 2017-11-05 16:42
If you do get the problem, please try it with this beta build:
https://jenkins.spacetux.net/job/KRASH/3/artifact/KRASH-0.5.26.zip
I added a check for a null at the only place I could find which might be causing it

**Comment by billw2012** [comment] 2017-12-19 18:56
I had this same problem, fixed by selecting "show all bodies in career". I am running with Kerbal Star Systems and the mod that hides bodies until you discover them (can't remember the name) and the whole SETI metamod pack and some other stuff. I would guess [https://github.com/linuxgurugamer/KRASH/blob/8595577be2d64cd092ce26beebeb09821fc5c641/Source/LaunchGUI.cs#L1112](url) might be the problem line given the work around.

I am not using the beta build you link above, I will try it next time I restart.
/edit NM the link is gone, and I am on 0.5.26 already.

**Comment by UnanimousCoward** [comment] 2018-04-06 08:08
I think I've managed to reliably recreate this bug. It occurs when KRASH, Kopernicus and TarsierSpaceTech are all installed at the same time. KRASH + Kopernicus = no problem. KRASH + TarsierSpaceTech = no problem. KRASH + Kopernicus + TarsierSpaceTech = no orbit selection window. 

I was able to reliably reproduce it in a test install (KSP 1.4.2, Windows 64-bit) with only these mods installed.

**Comment by jiversen** [comment] 2018-04-19 17:40
Yes! Thanks for the find, @UnanimousCoward. FWIW, as an additional data point, I confirm that removing Kopernicus (while leaving Tarsier installed) fixed the missing orbital tab for me. (KSP 1.3.1; KRASH 0.5.26; TST1:7.2; Kopernicus 2:release-1.3.1-7)

PS <OT> **Thank you** for maintaining this (and many other) great mods, @linuxgurugamer. I appreciate every time I play.

**Comment by denyasis** [comment] 2018-12-27 13:11
Hello ; I can confirm this error. It looks like it may be linked to "Research Bodies" by Tarsier Space Tech" in which certain planets are "hidden" from the player until they are discovered. In this case The orbit selection window is indeed blank and leaving it open long enough will cause the program to crash to desktop.
[KSP.log](https://github.com/linuxgurugamer/KRASH/files/2712497/KSP.log)

**Comment by linuxgurugamer** [comment] 2019-05-01 12:45
Is this still happening to people?

**Comment by Blothorn** [comment] 2019-05-08 21:19
Yes--same error
```
[EXC 13:47:22.350] NullReferenceException: Object reference not set to an instance of an object
	KRASH.LaunchGUI.drawSelectorWindow (Int32 id)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```
Relevant mods: Kopernicus, OPM, Research Bodies, Tarsier; I can't bisect on mods at the moment.

Interestingly, it happens in career regardless of whether "show all bodies in career" is selected, but works fine in sandbox.
[KSP.log](https://github.com/linuxgurugamer/KRASH/files/3159337/KSP.log)

**Comment by FunnyCorpse** [comment] 2020-11-07 13:57
Good day!
Has this been fixed?

**Closed as completed** 2020-12-26 21:47 UTC
