### ISSUE TITLE
Vessel jumps in orbit when time warping

### ISSUE THREAD

**Issue by tivec** [linuxgurugamer/KRASH#26] opened 2018-03-29 08:27 UTC
Hello! Whenever I simulate a flight and time warp, the vessel jumps forward in orbit as if skipping several minutes. See this video:

http://i.tivec.org/2018-03-29_10-01-51.mp4

Should be mentioned this is on 1.4.2, running KRASH 0.5.28.

**Comment by tivec** [comment] 2018-03-29 08:34
Some more details from my testing: I thought this had a relation to either Kerbal Joint Reinforcement or BetterTimeWarp. Removing those seems to have shortened the jump distance somewhat, but it is still skipping time.

**Comment by linuxgurugamer** [comment] 2018-03-29 10:23
Does it happen in 1.4.1?

**Comment by tivec** [comment] 2018-03-29 11:24
I do not remember this happening in 1.4.1, so it is possible it is related to the .2 update.

**Comment by OrbitalManeuvers** [comment] 2020-04-23 19:12
BTW and KJR are likely red herrings. I've never used either and this happens to me.

**Comment by JonnyOThan** [comment] 2020-09-01 16:06
This seems like a dupe of #15

**Comment by linuxgurugamer** [comment] 2021-08-29 14:43
Fixed by PR

**Closed as completed by linuxgurugamer** 2021-08-29 14:43 UTC
